Repository CFC-Servers/cfc_ulx_commands, pull requests merged in 2020-11, with the labels that each got.

#16 Add trainfuck ULX command
  lua/entities/train_fucked/cl_init.lua
  lua/entities/train_fucked/init.lua
  lua/entities/train_fucked/shared.lua
  lua/materials/cfc_trainfuck_kill_icon.vmt
  lua/materials/cfc_trainfuck_kill_icon.vtf
  lua/ulx/modules/sh/cfc_trainfuck.lua
  materials/cfc_trainfuck_kill_icon.vmt
  materials/cfc_trainfuck_kill_icon.vtf
Labels: enhancement

#22 Improve ulx brazil & ulx randtp
  lua/ulx/modules/sh/cfc_brazil.lua
Labels: bug, enhancement

#23 Feature/fix propify
  lua/ulx/modules/sh/cfc_propify.lua
Labels: bug, enhancement

#25 Fix unpropify and propHop errors
  lua/ulx/modules/sh/cfc_propify.lua
Labels: bug

#26 Fix error caused by a propified player disconnecting from the server
  lua/ulx/modules/sh/cfc_propify.lua
Labels: bug

#27 Fix unragdoll bug caused by propify
  lua/ulx/modules/sh/cfc_propify.lua
Labels: bug
